FROM registry.lab.example.com:5000/rhel10/rhel-bootc:10.0
ADD yum.repos.d /etc/yum.repos.d
RUN dnf install -y httpd && systemctl enable httpd && dnf clean all
RUN mkdir -p /webapp/html && chmod -R a+rX /webapp && \
  sed -i '1,$ s?/var/www/?/webapp/?' /etc/httpd/conf/httpd.conf
ADD html /webapp/html
