FROM registry.lab.example.com:5000/rhel10/rhel-bootc:10.0
ADD yum.repos.d /etc/yum.repos.d
RUN mkdir -p /usr/lib/bootc/kargs.d && \
  dnf install -y firewalld httpd cockpit && \
  dnf clean all && \
  firewall-offline-cmd --zone=public --add-service=http && \
  firewall-offline-cmd --zone=public --add-service=cockpit && \
  systemctl enable httpd && \
  systemctl enable firewalld && \
  systemctl enable cockpit.socket
ADD sysctl.d /usr/lib/sysctl.d
ADD kargs.d /usr/lib/bootc/kargs.d
ADD html /webapp/html
RUN sed -i '1,$ s?/var/www/?/webapp/?' /etc/httpd/conf/httpd.conf && \
  chmod -R a+rX /webapp && \
  semanage fcontext -a -t httpd_sys_content_t "/webapp(/.*)?" && \
  echo 'Webapp files are not here' > /var/www/html/index.html
