FROM registry.lab.example.com:5000/ubi10/ubi:10.0
ADD yum.repos.d /etc/yum.repos.d
RUN dnf install -y systemd httpd && systemctl enable httpd && dnf clean all
ADD html /var/www/html
ENTRYPOINT ["/lib/systemd/systemd"]
